fixed freezing script

diff --git a/hooks/symfony/pre-commit b/hooks/symfony/pre-commit
--- a/hooks/symfony/pre-commit
+++ b/hooks/symfony/pre-commit
@@ -9,22 +9,28 @@ PHP_CS_FIXER="vendor/bin/php-cs-fixer"
 PHP_CODE_SNIFFER="vendor/bin/phpcs"
 HAS_PHP_CS_FIXER=false
 HAS_PHP_CODE_SNIFFER=false
-FILES=$(git status --porcelain | grep -e '^[(A| )M]\(.*\).php$' | cut -c 3-)
 STATUS=1
 RED='\e[0;31m'
 GREEN='\e[0;32m'
 COLOR_RESET='\e[m'
 
-for FILE in $SFILES
-do
-	php -l -d display_errors=0 $PROJECT/$FILE
-	if [ $? != 0 ]
-	then
-		echo "Fix the error before commit."
-		exit 1
-	fi
-	FILES="$FILES $PROJECT/$FILE"
-done
+
+# @TODO support for files from cli args
+
+echo "Checking PHP Lint..."
+php -l -d display_errors=0 $PROJECT/$FILE
+if [ $? != 0 ]
+then
+    echo -e "$RED \U2717 Fix errors."
+    exit 1
+fi
+
+
+FILES=$(git status --porcelain | grep -e '^[(A| )M]\(.*\).php$' | cut -c 3-)
+
+if [ ${#FILES} -eq 0 ]; then
+    exit 0
+fi
 
 if [ -x "$PHP_CS_FIXER" ]; then
     HAS_PHP_CS_FIXER=true
@@ -33,7 +39,6 @@ fi
 if [ -x "$PHP_CODE_SNIFFER" ]; then
     HAS_PHP_CODE_SNIFFER=true
 fi
-
 
 if [ -L "$HOME/.config/composer/$PHP_CS_FIXER" ]; then
 	PHP_CS_FIXER="$HOME/.config/composer/$PHP_CS_FIXER"
@@ -50,9 +55,7 @@ else
 fi
 
 if $HAS_PHP_CODE_SNIFFER; then
-    git status --porcelain | grep -e '^[ M]\(.*\).php$' | cut -c 4- | while read line; do
-        ${PHP_CODE_SNIFFER} --standard=PSR2 $FILES;
-    done
+    ${PHP_CODE_SNIFFER} --standard=PSR2 $FILES;
 else
     echo ""
     echo "Please install php-code-sniffer:"
@@ -62,10 +65,10 @@ else
 fi
 
 STATUS=$?
-if [ $STATUS -gt 0 ]; then
-    echo -e "$RED \U2717 Please fix the errors above."
-else
+if [ $STATUS -eq 0 ]; then
     echo -e "$GREEN \U2713 Looking good."
+else
+    echo -e "$RED \U2717 Please fix the errors above."
 fi
 
 cd $CURRENT_DIRECTORY;
